main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.home_page, name='home_page'),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('routes/', include('routes.urls', namespace='routes')),
    # строка для ресейва

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

routes/urls.py
from django.urls import path
from routes import views

app_name = 'routes'

urlpatterns = [
    path('', views.view_routes, name='view_routes'),
    path('route/<slug:route_slug>/', views.route, name='route'),
]

schedule/urls.py
from django.urls import path
from routes import views

app_name = 'shedule'

urlpatterns = [
    path('', views.index, name='index'), 
    path('all_events/', views.all_events, name='all_events'), 
    path('add_event/', views.add_event, name='add_event'), 
    path('update/', views.update, name='update'),
    path('remove/', views.remove, name='remove'),
]



    

routes/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

# При реализации дополнительных опций
# class Category(models.Model):
#     """
#     Модель, описывающая услуги, оказываемые на сайте
#     """
#     title = models.CharField(max_length=150, unique=True, verbose_name='Название')
#     slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
#     description = models.TextField(blank=True, null=True, verbose_name='Описание категории')
#     image = models.ImageField(upload_to='category_images', blank=True, null=True, verbose_name='Изображение')

#     class Meta:
#         db_table = 'category'
#         verbose_name = 'Категорию'
#         verbose_name_plural = 'Категории'

#     def __str__(self):
#         return self.title



class Route(models.Model):
    """
    Модель существующих маршрутов
    """
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание маршрута')
    complexity = models.DecimalField(default=5.00, max_digits=3, decimal_places=2, verbose_name="Сложность" ) # Возможно переделать, чтобы не проводить доп.действий
    duration = models.PositiveSmallIntegerField(verbose_name='Продолжительность')
    distance = models.CharField(max_length=50, verbose_name='Протяженность')
    image = models.ImageField(upload_to='category_images', blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=6, decimal_places=2, verbose_name='Цена маршрута')
    # category = models.ForeignKey(to=Category, on_delete=models.SET_DEFAULT, verbose_name='Категория')

    class Meta:
        db_table = 'route'
        verbose_name = 'Маршрут'
        verbose_name_plural = 'Маршруты'
        ordering = ('id', )
    
    
    def __str__(self):
        return f'{self.name} - {self.price}'
    
    def get_absolute_url(self):
        return reverse("route", kwargs={"slug": self.slug})
    

schedule/models.py
from django.db import models
from routes.models import Route

class Events(models.Model):
    # name = models.ForeignKey(Route)
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255,null=True,blank=True)
    start = models.DateTimeField(null=True,blank=True)
    end = models.DateTimeField(null=True,blank=True)
 
    class Meta:  
        db_table = "tblevents"

main/views.py
from django.shortcuts import render

def home_page(request):
    return render(request, 'home.html')

routes/admin.py
from django.contrib import admin

from .models import Route

# @admin.register(Category)
# class CategoryAdmin(admin.ModelAdmin):
#     """
#     Админ-панель модели категорий
#     """

#     list_display = ('id', 'title', 'slug')
#     prepopulated_fields = {'slug' : ('title',)}

@admin.register(Route)
class RouteAdmin(admin.ModelAdmin):
    """Админ-панекль модели маршрутов"""

    list_display = ('id', 'name', 'complexity', 'price')
    prepopulated_fields = {'slug' : ('name', )}
    list_filter = ['complexity', 'price']

routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'routes'

routes/views.py
from django.shortcuts import render

from .models import Route


def view_routes(request):
    routes = Route.objects.all()

    context = {
        'title': 'Маршруты',
        'routes': routes
    }

    return render(request, 'routes/routes.html', context)


def route(request, route_slug=False):
    if route_slug:
        route = Route.objects.get(slug=route_slug)
    
    context = {
        'route': route
    }

    return render(request, 'routes/route.html', context)

schedule/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import Events

def index(request):
    all_events = Events.objects.all()
    context = {
        "events":all_events,
    }
    return render(request,'index.html',context)

def all_events(request):                                                                                                 
    all_events = Events.objects.all()                                                                                    
    out = []                                                                                                             
    for event in all_events:                                                                                             
        out.append({                                                                                                     
            'title': event.name,                                                                                         
            'id': event.id,                                                                                              
            'start': event.start.strftime("%m/%d/%Y, %H:%M:%S"),                                                         
            'end': event.end.strftime("%m/%d/%Y, %H:%M:%S"),                                                             
        })                                                                                                               
                                                                                                                      
    return JsonResponse(out, safe=False) 

def add_event(request):
    start = request.GET.get("start", None)
    end = request.GET.get("end", None)
    title = request.GET.get("title", None)
    event = Events(name=str(title), start=start, end=end)
    event.save()
    data = {}
    return JsonResponse(data)
 
def update(request):
    start = request.GET.get("start", None)
    end = request.GET.get("end", None)
    title = request.GET.get("title", None)
    id = request.GET.get("id", None)
    event = Events.objects.get(id=id)
    event.start = start
    event.end = end
    event.name = title
    event.save()
    data = {}
    return JsonResponse(data)
 
def remove(request):
    id = request.GET.get("id", None)
    event = Events.objects.get(id=id)
    event.delete()
    data = {}
    return JsonResponse(data)

routes/templates/routes/route.html
{% extends "home.html" %}

{% block content %}
    {{route.name}}
    {{route.description}}
    {{route.price}}
    {{route.complexity}}
{% endblock  %}

routes/templates/routes/routes.html
{% extends "home.html" %}

{% block title %}{{ title }}
{% endblock %}

{% block content %}
    {% for route in routes %}
        <a href="{% url "routes:route" route.slug %}">
            {{ route.name }}
            {{ route.price }}
        {% comment %} <h5><a href="{{ route.get_absolute_url }}">{{ route.name }}</a></h5> {% endcomment %}
        {% comment %} {{ route.price }}  {% endcomment %}
        <p></p>
        
    {% endfor %}
{% endblock %}

schedule/templates/shedule/base_cal.html
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 9 Ajax FullCalender CRUD (Create, Read, Update and Delete)</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
      
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.js"></script>
</head>
<body>
<div class="container">
 <div class="row">
    <h4>Python Django Ajax FullCalender CRUD (Create, Read, Update and Delete)</h4> 
    {% block content %}{% endblock %}
 </div>
</div>
<script>
   $(document).ready(function () {
       var calendar = $('#calendar').fullCalendar({
           header: {
               left: 'prev,next today',
               center: 'title',
               right: 'month,agendaWeek,agendaDay'
           },
           events: '/all_events',
           selectable: true,
           selectHelper: true,
           editable: true,
           eventLimit: true,
           select: function (start, end, allDay) {
               var title = prompt("Enter Event Title");
               if (title) {
                   var start = $.fullCalendar.formatDate(start, "Y-MM-DD HH:mm:ss");
                   var end = $.fullCalendar.formatDate(end, "Y-MM-DD HH:mm:ss");
                   $.ajax({
                       type: "GET",
                       url: '/add_event',
                       data: {'title': title, 'start': start, 'end': end},
                       dataType: "json",
                       success: function (data) {
                           calendar.fullCalendar('refetchEvents');
                           alert("Added Successfully");
                       },
                       error: function (data) {
                           alert('There is a problem!!!');
                       }
                   });
               }
           },
           eventResize: function (event) {
               var start = $.fullCalendar.formatDate(event.start, "Y-MM-DD HH:mm:ss");
               var end = $.fullCalendar.formatDate(event.end, "Y-MM-DD HH:mm:ss");
               var title = event.title;
               var id = event.id;
               $.ajax({
                   type: "GET",
                   url: '/update',
                   data: {'title': title, 'start': start, 'end': end, 'id': id},
                   dataType: "json",
                   success: function (data) {
                       calendar.fullCalendar('refetchEvents');
                       alert('Event Update');
                   },
                   error: function (data) {
                       alert('There is a problem!!!');
                   }
               });
           },
 
           eventDrop: function (event) {
               var start = $.fullCalendar.formatDate(event.start, "Y-MM-DD HH:mm:ss");
               var end = $.fullCalendar.formatDate(event.end, "Y-MM-DD HH:mm:ss");
               var title = event.title;
               var id = event.id;
               $.ajax({
                   type: "GET",
                   url: '/update',
                   data: {'title': title, 'start': start, 'end': end, 'id': id},
                   dataType: "json",
                   success: function (data) {
                       calendar.fullCalendar('refetchEvents');
                       alert('Event Update');
                   },
                   error: function (data) {
                       alert('There is a problem!!!');
                   }
               });
           },
 
           eventClick: function (event) {
               if (confirm("Are you sure you want to remove it?")) {
                   var id = event.id;
                   $.ajax({
                       type: "GET",
                       url: '/remove',
                       data: {'id': id},
                       dataType: "json",
                       success: function (data) {
                           calendar.fullCalendar('refetchEvents');
                           alert('Event Removed');
                       },
                       error: function (data) {
                           alert('There is a problem!!!');
                       }
                   });
               }
           },
 
       });
   });
 
</script>
</body>
</html>

schedule/templates/shedule/calendar.html
{% extends "base.html" %}
   
{% block title %}Python Django Ajax FullCalender CRUD (Create, Read, Update and Delete){% endblock title %}
   
{% block content %}
<div class="col-md-12">    
    <div id='calendar'></div> 
</div> 
{% endblock content %} 

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
            Document {% endblock%} </title>
</head>
<body>
    <h1> {% block content %}
        Home - page
        {% endblock %}</h1>
</body>
</html>